language: python
python:
  - 3.6
before_install:
  - chmod +x setup.py
  - pip install codecov
install:
  - pip install -r requirements.txt
env:
  - FLASK=1.0.2
script:
  - ./setup.py test
after_success:
  - codecov
