language: python
python:
  - 3.6
before_install:
  - chmod +x setup.py
install:
  - pip install flask
  - pip install -r requirements.txt
  - pip install codecov
script:
  - ./setup.py test
after_success:
  - codecov
