language: python
python:
  - 3.6
before_install:
  - chmod +x setup.py
install:
  - pip install -r requirements.txt
env:
  - FLASK=1.0.2
script:
  - ./setup.py test
after_success:
  - codecov --token="625ecb3f-fb87-4093-8e25-e126fb4f71f0"
